[#476] favourites icon turn red on mouse hover
CivicTechFredericton/mealplanner pull request #477
Opened 2023-07-12 14:14 UTC by okayyjen

**Describe the technical changes contained in this PR**
in the MealPlans.tsx file, I have added code to the IconButton

**Previous behaviour**
When the user hovers their mouse over the favourites/heart icon, the icon stays a grey colour:
![image](https://github.com/CivicTechFredericton/mealplanner/assets/60271693/55cb1cf2-80b7-45c3-b98b-892d86fb5eb2)

**New behaviour**
When the user hovers their mouse over the favourites/heart icon, the icon now turns red:
![image](https://github.com/CivicTechFredericton/mealplanner/assets/60271693/5da5fcb9-1d3d-4362-9f29-9930d3f31c3b)

**Related issues addressed by this PR**
Fixes #476

**Have the following been addressed?**
- [ ] Have test cases been created for all of the changes?
- [ ] Do all of the test cases pass?
- [ ] Has the testing been done using the default docker-compose environment?
- [ ] Are documentation changes required?
- [ ] Does this change break or alter existing behaviour?

2024-02-10 15:46 UTC, introkun approved these changes
Looks good to me

2024-02-10 18:58 UTC, okayyjen commented
> Looks good to me

thank you! But I actually think I have to fix it so that the heart stays red once you click on it. I am getting to it now

2024-02-15 15:12 UTC, shanthisa requested changes

2024-02-15 15:12 UTC, shanthisa commented on mealplanner-ui/src/pages/MealPlans/MealPlans.tsx
> +          <IconButton aria-label="add to favorites" sx={{ "& :hover": { color: "#dc143c" } }}>
Need to add the color from the theme -> secondary -> dark. You can access it with palette.

2024-03-22 20:23 UTC, closed without merging