505 admin UI searchbar products
CivicTechFredericton/mealplanner pull request #506
Opened 2024-02-09 21:38 UTC by RLCASTRO

Created a search bar input component in the Products page that takes the data, queries the database and returns to the parent component an array of IDs with the items that match the query result.

In the parent component, the array of IDs is passed as a value to the "filter" prop of the List component to apply a filter with the group of IDs.

![image](https://github.com/CivicTechFredericton/mealplanner/assets/37277959/24a2c415-1887-4432-bc87-fc854837d540)

2024-02-12 19:02 UTC, shanthisa requested changes
Good work. I have made a few suggestions / observations. Please have a look at them.

2024-02-12 19:02 UTC, shanthisa commented on admin-ui/src/Products/service.ts
> +            { nameEn: { includes: $searchString } }
Instead of includes, if we have it as includesInsensitive, this can include case-insensitive searches. For example, if the entry is "HIMALAYAN SALT". The search 'himala' will also work for includesInsensitive whereas it won't work for includes.

2024-02-12 19:02 UTC, shanthisa commented on admin-ui/src/Products/service.ts
> +  console.log(result);
Please remove console.log statements after debugging

2024-02-12 19:02 UTC, shanthisa commented on admin-ui/src/Products/service.ts
> +): Promise<any> => {
Isn't this `Promise<[string]>` ?

2024-02-12 19:02 UTC, shanthisa commented on admin-ui/src/Products/ProductList.tsx
> +  const [data, setData] = useState<ProductType[]>([]);
Shouldn't the type of data be string[] instead of ProductType[] because the data here is assigned to rowId. Actually you have typed result: any for extractIdsFromResults and Promise<any> for getSearchByString. Hence TypeScript did not complain this. By default if we do not use `any` type TypeScript will guide us with types when we make a mistake.

2024-02-12 19:02 UTC, shanthisa commented on admin-ui/src/Products/service.ts
> +const extractIdsFromResult = (result: any) => {
This should have `result: QueryResponse`
For ease of understanding, I am giving you the types. I renamed ProductType to ProductResultType and described QueryResponse type.
```
export type ProductResultType = {
  rowId: string;
};
type QueryResponse = {
  data: {
    query: {
      products: {
        edges: [{node: ProductResultType}]
      }
    }
  }
}

2024-02-12 19:02 UTC, shanthisa commented on admin-ui/src/Products/ProductList.tsx
> +    console.log(data);
I think useEffect is not required. You may remove it if it doesn't serve a purpose.

2024-02-12 19:02 UTC, shanthisa commented on admin-ui/src/Products/service.ts
> +    .then((result) => extractIdsFromResult(result));
When we use await, we generally don't use `.then`.
I would rather write this as

```
const result = await client.query({...});
const ids = extractIdsFromResult(result);
return ids;

2024-02-12 19:02 UTC, shanthisa commented on admin-ui/src/components/CustomSearchInput.tsx
> +  onSearch: (data: any) => void;
Type can be `data: string[]`

2024-02-13 20:02 UTC, RLCASTRO commented on admin-ui/src/Products/service.ts
> +            { nameEn: { includes: $searchString } }
Updated the query to use includesInsensitive. Nice catch. Thank you.

2024-02-13 20:19 UTC, RLCASTRO commented on admin-ui/src/Products/ProductList.tsx
> +  const [data, setData] = useState<ProductType[]>([]);
Got it. Updated the data to receive a String[] instead.

2024-02-13 20:24 UTC, RLCASTRO commented on admin-ui/src/Products/ProductList.tsx
> +    console.log(data);
Done. Thank you.

2024-02-14 18:04 UTC, RLCASTRO commented on admin-ui/src/Products/service.ts
> +    .then((result) => extractIdsFromResult(result));
I don't know why I did this, thanks for the notice!

2024-02-14 18:10 UTC, RLCASTRO commented on admin-ui/src/Products/service.ts
> +): Promise<any> => {
awesome, an string[] actually. Thank you again.

2024-02-14 18:30 UTC, RLCASTRO commented on admin-ui/src/Products/service.ts
> +  console.log(result);
Done. Thank you.

2024-02-14 19:02 UTC, RLCASTRO commented on admin-ui/src/Products/service.ts
> +const extractIdsFromResult = (result: any) => {
Update done. It is much more clear right now. Thank you for that.

2024-02-14 21:06 UTC, RLCASTRO commented on admin-ui/src/components/CustomSearchInput.tsx
> +  onSearch: (data: any) => void;
Done. Thank you again.

2024-02-15 02:03 UTC, introkun commented
Fixes #505

2024-02-19 21:31 UTC, shanthisa commented
@ala-sk98 - Can you please test this and confirm whether it works in this branch?

2024-02-22 02:58 UTC, ala-sk98 commented
> @ala-sk98 - Can you please test this and confirm whether it works in this branch?

Sure. I'm working on it.

2024-02-23 01:17 UTC, shanthisa submitted a review, later dismissed
LGTM 👍

2024-02-23 01:18 UTC, shanthisa approved these changes
Changed the base branch to v2. So had to approve again before merge.

2024-02-23 01:18 UTC, merged

2024-03-26 13:15 UTC, ala-sk98 commented
QA done.
Test case[AA-SearchBarProducts-023](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0#test-case-id-AA-SearchBarProducts-023) : Failed;  Issue #593 created to address it.