[#603] - shopping list feature WIP
CivicTechFredericton/mealplanner pull request #611
Opened 2024-04-03 13:04 UTC by okayyjen

**Describe the technical changes contained in this PR**
Be clear about purpose and scope of the change

**Previous behaviour**
Describe the product behaviour before this change, if relevant

**New behaviour**
Describe how product behaviour is altered by this change

**Related issues addressed by this PR**
List issue numbers using the "Fixes #xxx" syntax

**Have the following been addressed?**
- [ ] Have test cases been created for all of the changes?
- [ ] Do all of the test cases pass?
- [ ] Has the testing been done using the default docker-compose environment?
- [ ] Are documentation changes required?
- [ ] Does this change break or alter existing behaviour?

2024-04-08 12:35 UTC, shanthisa requested changes
Meal name is not unique in the database. So data entry people may put two different meals with the same names, though the chances are less. So if identify them with meal id it will be unique.

2024-04-08 12:35 UTC, shanthisa commented on mealplanner-ui/src/pages/ShoppingList.tsx
> +    if (mealName) {
What if the name is duplicate across two different meals. The meal id is the unique value here

2024-04-08 12:39 UTC, shanthisa commented
This has come out very well. On looking at the screenshot, I had another perspective. When there are multiple meals, the rows of the meals and the quantity and unit will match, however the products list won't match with the row lines. Since these columns are tightly coupled when compared to others, it would be more clearer if we put them in the same column.
Eg:

---------------------------------------------
|| Ingredient | Meal - Quanity / Unit | Product ||
---------------------------------------------
| Coconut | Coriander chutney - 0.5 / cup | Shredded Coconut |

2024-04-08 23:58 UTC, okayyjen commented on mealplanner-ui/src/pages/ShoppingList.tsx
> +    if (mealName) {
@shanthisa Thank you, I have changed the logic of the code to use mealId

2024-04-08 23:59 UTC, okayyjen commented
@shanthisa hello, I have applied all the changes you have requested

2024-04-09 15:28 UTC, shanthisa approved these changes
LGTM 👍

2024-04-09 15:29 UTC, merged