V2
CivicTechFredericton/mealplanner pull request #643
Opened 2024-04-16 20:45 UTC by MohamedHAlsadek

**Describe the technical changes contained in this PR**
Be clear about purpose and scope of the change

**Previous behaviour**
Describe the product behaviour before this change, if relevant

**New behaviour**
Describe how product behaviour is altered by this change

**Related issues addressed by this PR**
List issue numbers using the "Fixes #xxx" syntax

**Have the following been addressed?**
- [ ] Have test cases been created for all of the changes?
- [ ] Do all of the test cases pass?
- [ ] Has the testing been done using the default docker-compose environment?
- [ ] Are documentation changes required?
- [ ] Does this change break or alter existing behaviour?

2024-05-02 01:20 UTC, rorybray requested changes
Just a couple of changes needed

2024-05-02 01:20 UTC, rorybray commented on docs/2-Logout.md
> +![Logout Page](https://snipboard.io/lMLQaj.jpg)
Please check images in to the docs/ directory alongside the .md files

2024-05-02 01:20 UTC, rorybray commented on docs/1-Login..md
> +![Login Page](https://snipboard.io/bVYejn.jpg)
Please check images in to the docs/ directory alongside the .md files

2024-05-02 01:20 UTC, rorybray commented on docs/1-Login..md
> +    - Click on the "LOGIN" button in the login window to access your account page
we can replace this with a brief description of what to expect. Clicking doesn't come until the next step.

2024-05-02 01:20 UTC, rorybray commented on docs/3-Creat a meal Plan.md
> +    - Select "Create New Meal Plan"
This doesn't mention the assign user drop-down or start date

2024-05-03 01:50 UTC, MohamedHAlsadek commented on docs/2-Logout.md
> +![Logout Page](https://snipboard.io/lMLQaj.jpg)
Done

2024-05-03 01:50 UTC, MohamedHAlsadek commented on docs/1-Login..md
> +![Login Page](https://snipboard.io/bVYejn.jpg)
Done

2024-05-03 01:51 UTC, MohamedHAlsadek commented on docs/1-Login..md
> +    - Click on the "LOGIN" button in the login window to access your account page
Done

2024-05-03 01:51 UTC, MohamedHAlsadek commented on docs/3-Creat a meal Plan.md
> +    - Select "Create New Meal Plan"
Done

2024-05-07 22:22 UTC, rorybray requested changes
One small thing I didn't notice before. Could you rename the file from 1-Login..md to 1-Login.md (take out the extra dot)

2024-05-08 13:00 UTC, MohamedHAlsadek reviewed
Done. Thanks, Rory.

2024-05-21 22:56 UTC, rorybray approved these changes
LGTM

2024-05-21 22:56 UTC, merged