646 search product
CivicTechFredericton/mealplanner pull request #648
Opened 2024-04-18 14:09 UTC by priyaguntupalli5

**Describe the technical changes contained in this PR**
Be clear about purpose and scope of the change

**Previous behaviour**
Describe the product behaviour before this change, if relevant

**New behaviour**
Describe how product behaviour is altered by this change

**Related issues addressed by this PR**
Fixes #646 

**Have the following been addressed?**
- [ ] Have test cases been created for all of the changes?
- [ ] Do all of the test cases pass?
- [ ] Has the testing been done using the default docker-compose environment?
- [ ] Are documentation changes required?
- [ ] Does this change break or alter existing behaviour?

2024-04-18 18:39 UTC, shanthisa requested changes

2024-04-18 18:39 UTC, shanthisa commented on backend/db_migrations/000008_match.up.sql
> +    FROM app.product p where i.product_keyword ilike ANY(p.product_keywords);
As mentioned before, you cannot edit existing migrations. Please create a new migration with this same code. Code is correct.

2024-04-23 23:42 UTC, shanthisa requested changes
Should not have the other migration file 019-646-keyword-products.sql. /migrations folder is outdated.

2024-04-24 13:32 UTC, priyaguntupalli5 commented
Removed it. Thanks!

2024-04-24 19:13 UTC, shanthisa approved these changes
LGTM 👍

2024-04-24 19:13 UTC, merged