Calenda documentation
CivicTechFredericton/mealplanner pull request #660
Opened 2024-04-27 18:05 UTC by folaj034

**Describe the technical changes contained in this PR**
Be clear about purpose and scope of the change

**Previous behaviour**
Describe the product behaviour before this change, if relevant

**New behaviour**
Describe how product behaviour is altered by this change

**Related issues addressed by this PR**
List issue numbers using the "Fixes #xxx" syntax

**Have the following been addressed?**
- [ ] Have test cases been created for all of the changes?
- [ ] Do all of the test cases pass?
- [ ] Has the testing been done using the default docker-compose environment?
- [ ] Are documentation changes required?
- [ ] Does this change break or alter existing behaviour?

2024-05-02 02:28 UTC, rorybray requested changes

2024-05-02 02:28 UTC, rorybray commented on docs/Calenda.md
> +##Mealplan Calenda
check spelling

2024-05-02 02:28 UTC, rorybray commented on docs/Calenda.md
> + ![calenda](https://snipboard.io/eMlWHc.jpg)
Please checkin images alongside .md files.

2024-05-21 22:59 UTC, rorybray requested changes
Still need the image links to be updated. They should look like:

![calendar](calendar1.png) 

and so on.

2024-05-22 00:12 UTC, merged

2024-05-22 02:36 UTC, folaj034 commented
Hi Rory,
I didn't realize the imagelink  wasn't updated properly. I'll update and
revert.

BR

On Tue, May 21, 2024 at 7:59 PM Rory ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Still need the image links to be updated. They should look like:
>
> [image: calendar] <http://calendar1.png>
>
> and so on.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CivicTechFredericton/mealplanner/pull/660#pullrequestreview-2069763562>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIDWY2C4PE735DD2QN53P6DZDPGURAVCNFSM6AAAAABG4IULOOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRZG43DGNJWGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-22 13:45 UTC, folaj034 commented
Hi Rory,
I updated the image link. Pls confirm.

Regards


On Tue, May 21, 2024 at 11:35 PM Fola Jay ***@***.***> wrote:

> Hi Rory,
> I didn't realize the imagelink  wasn't updated properly. I'll update and
> revert.
>
> BR
>
> On Tue, May 21, 2024 at 7:59 PM Rory ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Still need the image links to be updated. They should look like:
>>
>> [image: calendar] <http://calendar1.png>
>>
>> and so on.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/CivicTechFredericton/mealplanner/pull/660#pullrequestreview-2069763562>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BIDWY2C4PE735DD2QN53P6DZDPGURAVCNFSM6AAAAABG4IULOOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRZG43DGNJWGI>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>